CREATE TABLE MY_MEMBER(
	MEM_NUM INT AUTO_INCREMENT PRIMARY KEY
	, MEM_ID VARCHAR(50) NOT NULL
	, MEM_PW VARCHAR(50) NOT NULL
	, MEM_NAME VARCHAR(20) NOT NULL
	, MEM_AGE INT 
	, EMAIL VARCHAR(50)
);

INSERT INTO MY_MEMBER VALUES(1, 'MEMID', 'MEMPW', 'MEMNAME', 20 , 'EMAIL');

DELETE FROM MY_MEMBER;

SELECT * FROM MY_MEMBER;

UPDATE MY_MEMBER
SET MEM_NAME='김자바', MEM_ID='KIMJAVA'
WHERE MEM_NUM=1;

SELECT * FROM emp;
SELECT * FROM dept;
