-- 1.
CREATE TABLE MY_MEMBER(
	MEM_NUM INT AUTO_INCREMENT PRIMARY KEY
	, MEM_ID VARCHAR(50) NOT NULL
	, MEM_PW VARCHAR(50) NOT NULL
	, MEM_NAME VARCHAR(20) NOT NULL
	, MEM_AGE INT 
	, EMAIL VARCHAR(50)
);

-- 2.
INSERT INTO MY_MEMBER VALUES(1, 'MEMID', 'MEMPW', 'MEMNAME', 20 , 'EMAIL');
DELETE FROM MY_MEMBER;

SELECT * FROM MY_MEMBER;

-- 3.
UPDATE MY_MEMBER
SET MEM_NAME='김자바', MEM_ID='KIMJAVA'
WHERE MEM_NUM=1;

SELECT * FROM emp;
SELECT * FROM dept;

-- 4.
SELECT EMPNO, ENAME, SAL, COMM
FROM emp
WHERE SAL<=500
AND SAL>= 300
AND COMM IS NOT NULL;

-- 5.
SELECT EMPNO, ENAME, HIREDATE
FROM emp
WHERE ENAME LIKE '%기'
OR ENAME LIKE '%김%'
ORDER BY EMPNO DESC;

