CREATE TABLE HOS_MEMBER(
	MEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, MEM_NAME VARCHAR(10) NOT NULL
	, MEM_BIRTH VARCHAR(12) NOT NULL
	, MEM_TEL VARCHAR(20) NOT NULL
	, MEM_ADDR VARCHAR(50) NOT NULL
	, MEM_ID VARCHAR(10) UNIQUE
	, MEM_PW VARCHAR(10) 
	, MEM_GEN VARCHAR(10) NOT NULL
);

CREATE TABLE HOS_STAFF(
	STAFF_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STAFF_NAME VARCHAR(10) NOT NULL
	, STAFF_ROLE VARCHAR(10) DEFAULT 'STAFF'
	, STAFF_BIRTH VARCHAR(12) NOT NULL
	, STAFF_TEL VARCHAR(20) NOT NULL
	, STAFF_ADDR VARCHAR(50) NOT NULL
	, STAFF_ID VARCHAR(10) UNIQUE
	, STAFF_PW VARCHAR(10) 
	, STAFF_GEN VARCHAR(10) NOT NULL
	, PART_NUM INT NOT NULL REFERENCES HOS_PART(PART_NUM) ON DELETE CASCADE
);

CREATE TABLE HOS_PART(
	PART_NUM INT PRIMARY KEY AUTO_INCREMENT
	, PART_NAME VARCHAR(10) NOT NULL
);

CREATE TABLE HOS_BOARD(
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BOARD_TITLE VARCHAR(50) NOT NULL
	, BOARD_CONTENT VARCHAR(100) NOT NULL
	, STAFF_NUM INT NOT NULL REFERENCES hos_staff(STAFF_NUM) ON DELETE CASCADE
	, BOARD_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE HOS_Q(
	Q_NUM INT PRIMARY KEY AUTO_INCREMENT
	, MEM_NUM INT NOT NULL REFERENCES hos_member(MEM_NUM) ON DELETE CASCADE
	, Q_TITLE VARCHAR(50) NOT NULL
	, Q_CONTENT VARCHAR(100) NOT NULL
	, Q_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE HOS_A(
	A_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STAFF_NUM INT NOT NULL REFERENCES hos_staff(STAFF_NUM) ON DELETE CASCADE
	, A_CONTENT VARCHAR(100) NOT NULL
	, A_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, Q_NUM INT NOT NULL REFERENCES HOS_Q(Q_NUM) ON DELETE CASCADE
);

CREATE TABLE hos_chart(
	CHART_NUM INT PRIMARY KEY AUTO_INCREMENT
	, MEM_NUM INT NOT NULL REFERENCES hos_res(MEM_NUM) ON DELETE CASCADE
	, IS_NOW VARCHAR(50) NOT NULL
);

-- 환자 테이블(회원가입이랑 별도)
CREATE TABLE HOS_PATIE (
	PATIE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, PATIE_NAME VARCHAR(50) NOT NULL
	, PATIE_TEL VARCHAR(50) NOT NULL
	, PATIE_BIRTH VARCHAR(50) NOT NULL
	, PATIE_ADDR VARCHAR(50) NOT NULL
	, PATIE_GEN VARCHAR(5) NOT NULL
);
-- 진료 테이블
CREATE TABLE HOS_REC (
	REC_NUM INT PRIMARY KEY AUTO_INCREMENT
	, REC_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	, IS_REC VARCHAR(5) NOT NULL DEFAULT 'N'
	, REC_STATUS VARCHAR(10) NOT NULL DEFAULT '대기'
	, REC_DETAIL VARCHAR(50) 
	, PATIE_NUM INT NOT NULL REFERENCES HOS_PATIE(PATIE_NUM) ON DELETE CASCADE
	, STAFF_NUM INT NOT NULL REFERENCES hos_staff(STAFF_NUM) ON DELETE CASCADE
);
-- 개인 일정
CREATE TABLE hos_schedule (
	SCH_NUM INT PRIMARY KEY AUTO_INCREMENT
	, SCH_SDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	, SCH_EDATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	, SCH_TITLE VARCHAR(50) NOT NULL
	, SCH_CONTENT VARCHAR(100)
	, COLOR VARCHAR(10)
	, ALL_DAY VARCHAR(5)
	, STAFF_NUM INT NOT NULL REFERENCES hos_staff(STAFF_NUM) ON DELETE CASCADE
);
SELECT * FROM hos_rec;


-- ======================= 공급처 ==================================

-- 발주처 테이블(발주처)
CREATE TABLE SUP(
	SUP_NUM INT PRIMARY KEY AUTO_INCREMENT -- 발주처 번호
	, SUP_NAME VARCHAR(50) NOT NULL -- 발주처 이름
);

-- 병원 테이블
CREATE TABLE CUS(
	CUS_NUM INT PRIMARY KEY AUTO_INCREMENT -- 병원 번호
	, CUS_NAME VARCHAR(50) NOT NULL -- 병원 이름
	, CUS_ADDR VARCHAR(100) NOT NULL -- 병원 주소
	, CUS_TEL VARCHAR(50) NOT NULL -- 병원 연락처
);

-- 상품 타입
CREATE TABLE ITEM_TYPE(
	TYPE_NUM INT PRIMARY KEY AUTO_INCREMENT -- 상품 타입  번호
	, TYPE_NAME VARCHAR(100) NOT NULL -- 상품 타입  이름
);


-- 상품 테이블(발주처)
CREATE TABLE ITEM(
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT -- 상품 번호
	, ITEM_NAME VARCHAR(100) NOT NULL -- 상품 이름
	, PRICE INT NOT NULL -- 가격
	, STOCK INT NOT NULL -- 재고량
	, ITEM_CODE VARCHAR(100) NOT NULL -- 상품 코드
	, ITEM_DETAIL VARCHAR(100) -- 상품 설명
	, ITEM_IMG VARCHAR(200)  -- 상품 이미지
	, TYPE_NUM INT NOT NULL REFERENCES ITEM_TYPE(TYPE_NUM) ON DELETE CASCADE -- 상품 타입 번호
	, SUP_NUM INT NOT NULL REFERENCES SUP(SUP_NUM) ON DELETE CASCADE -- 발주처 번호
);

-- 배송상태
CREATE TABLE DELIVER(
	DELI_NUM INT PRIMARY KEY AUTO_INCREMENT -- 배송 번호
	, DELI_STATUS VARCHAR(100) DEFAULT '주문확인중' -- 배송 상태 (주문확인중, 상품준비중, 배송중, 배송완료)
);

SELECT * FROM DELIVER;


-- 출하/입고 상품 테이블 (주문 내역)
CREATE TABLE ORDER_ITEM(
	ORDER_NUM INT PRIMARY KEY AUTO_INCREMENT -- 주문 번호
	, ORDER_CNT INT NOT NULL -- 구매수량
	, ITEM_NUM INT NOT NULL REFERENCES ITEM(ITEM_NUM) ON DELETE CASCADE --  상품 번호
	, ORDER_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP -- 구매한 시간
	, DEPART_TIME DATETIME -- 출발 시간
	, ARRIVE_TIME DATETIME -- 도착 시간
	, CUS_NUM INT NOT NULL REFERENCES CUS(CUS_NUM) ON DELETE CASCADE -- 병원 번호
	, DELI_NUM INT NOT NULL REFERENCES DELIVER(DELI_NUM) ON DELETE CASCADE -- 배송 상태
);

SELECT * FROM ORDER_ITEM;

CREATE TABLE SUP_MEMBER(
	SUPM_NUM INT PRIMARY KEY AUTO_INCREMENT -- 회원 번호
	, SUPM_ROLE VARCHAR(100) NOT NULL DEFAULT 'STAFF' -- 권한
	, SUPM_NAME VARCHAR(50) NOT NULL -- 이름
	, SUPM_ADDR VARCHAR(100) NOT NULL -- 주소
	, SUPM_BIRTH VARCHAR(50) NOT NULL -- 생년월일
	, SUPM_TEL VARCHAR(50) NOT NULL -- 전화번호
	, SUPM_ID VARCHAR(50) NOT NULL UNIQUE -- 아이디
	, SUPM_PW VARCHAR(50) NOT NULL -- 비밀번호
);


-- 발주처 테이블에 기본값 삽입
INSERT INTO SUP (SUP_NAME) VALUES 
('발주처 A'),
('발주처 B'),
('발주처 C');

-- 병원 테이블에 기본값 삽입
INSERT INTO CUS (CUS_NAME, CUS_ADDR, CUS_TEL) VALUES 
('병원 A', '서울시 강남구 1번지', '010-1234-5678'),
('병원 B', '부산시 해운대구 2번지', '010-2345-6789'),
('병원 C', '대구시 중구 3번지', '010-3456-7890');

-- 상품 타입 테이블에 기본값 삽입
INSERT INTO ITEM_TYPE (TYPE_NAME) VALUES 
('의약품'),
('소모품'),
('기타');

-- 상품 테이블에 기본값 삽입
INSERT INTO ITEM (ITEM_NAME, PRICE, STOCK, ITEM_CODE, ITEM_DETAIL, TYPE_NUM, SUP_NUM) VALUES 
('상품 A', 10000, 50, 'ITEM001', '상품 A 설명', 1, 1),
('상품 B', 15000, 30, 'ITEM002', '상품 B 설명', 2, 2),
('상품 C', 20000, 20, 'ITEM003', '상품 C 설명', 3, 3);


-- 배송상태 테이블에 기본값 삽입
INSERT INTO DELIVER (DELI_STATUS) VALUES 
('주문확인중'),
('상품준비중'),
('배송중'),
('배송완료'),
('주문취소');

-- 출하/입고 상품 테이블에 기본값 삽입
INSERT INTO ORDER_ITEM (ORDER_CNT, ITEM_NUM, ORDER_DATE, DEPART_TIME, ARRIVE_TIME, CUS_NUM, DELI_NUM) VALUES 
(5, 1, '2024-09-01 12:00:00', '2024-09-01 12:30:00', '2024-09-01 14:00:00', 1, 1),
(10, 2, '2024-09-02 13:00:00', '2024-09-02 14:30:00', '2024-09-02 16:00:00', 2, 2),
(3, 3, '2024-09-03 14:00:00', '2024-09-03 15:30:00', '2024-09-03 16:30:00', 3, 3);


-- 발주처 회원 테이블에 기본값 삽입
INSERT INTO SUP_MEMBER (SUPM_ROLE, SUPM_NAME, SUPM_ADDR, SUPM_BIRTH, SUPM_TEL, SUPM_ID, SUPM_PW) VALUES 
('STAFF', '김철수', '서울시 강남구 4번지', '1990-01-01', '010-1111-2222', '3333', '3333'),
('STAFF', '이영희', '부산시 해운대구 5번지', '1985-02-02', '010-3333-4444', '2222', '2222'),
('ADMIN', '박민수', '대구시 중구 6번지', '1992-03-03', '010-5555-6666', '1111', '1111');

